= Digital Combat Simulator

== My projects

Some DCS related things I have made:

* https://github.com/bjanders/dcs-api[Digital Combat Simulator API
information] The purpose of this is to pull information on the controls and
gauges of the aircraft directly from the LUA source files of DCS and
collecting it in structured JSON files with minimal manual work. This
information can then be utilized in client and server software for
integrating with DCS, for example, if you want to make real controllers
and gauges for DCS, or build a complete cockpit. No software for doing the
actual integration is here.
* https://github.com/bjanders/dcs-master[Digital Combat Simulator cockpit
integration server] This is a "plugin" for DCS through which you can
easily control every single switch and get the information from every
single gauge from any aircraft. This builds on the API information in
the project mentioned above. If the information is in the API, then it
provides extended functionality, but even if the information is not yet
extracted you can still control the aircraft and get gauge information.
This is just a server with a simple protocol so that you can easily
make your own client the way you want.
* https://github.com/bjanders/fpanels[Go library for interacting with
Logitech/Saitek flight panels] Not strictly a DCS specific project,
but can be used with DCS related projects. This is a Go library through
which can interact with the Logitech/Saitek flight panels. All switches and
displays and LEDs can be controlled. It's just a library, not an application
(although it contains a couple of test applications).
* https://github.com/bjanders/dcs-master-panels[Logitech/Saitek flight
panels for DCS] With this application you can use the Logitech/Saitek
flight panels with DCS. It uses the https://github.com/bjanders/fpanels[Go
library] mentioned above to connect to the panels and talks to DCS the
https://github.com/bjanders/dcs-master[DCS server] also mentioned above. You
can make your own routing rules so that you can route any switch to any
control in any plane and route any information from any plane to any
display on the panels. Documentation is still a bit lacking unfortunately.

== Misc

=== Kneeboards

The format should be JPG or PNG and the size should be 1024x680 or 1024x768 pixels.

Kneeboards are placed in the following locations:

* C:\Users\<User Name>\Saved Games\DCS\Kneeboard
* C:\Users\<User Name>\Saved Games\DCS\Kneeboard\A-10C

The above is documented in the DCS user manual.

Kneeboards can easily be created with https://mupdf.com/[mutool.exe], for example:
----
mutool.exe convert -o Ka-50-%d.png -F png -O width=768,height=1024 Ka-50_checklist.pdf
----

I create my checklists in https://www.libreoffice.org/[LibreOffice] Calc, export the sheets to PDF with pages in 3:4 ratio (18x24 cm), and then convert to PNGs with the above command.

Links:

* http://www.dcskneeboardbuilder.com/[Kneeboard Builder] (Seems to violate open source license)
* https://www.airgoons.com/w/Digital_Combat_Simulator


=== Other

* DemoMods
* VR mouse
